### ISSUE TITLE
Style of API Reference page is different from other 3 developer. pages.

### ISSUE THREAD

**Issue by RunninglVlan** [playcanvas/developer.playcanvas.com#11]
Is it supposed to be like this?

![](http://i.imgur.com/WCcZnXJ.png)

On API Reference PlayCanvas logo is bigger and behind upper panel, fonts are different, menu item is highlighted etc.

**Comment by willeastcott** [comment]
With the new design for the developer site, this problem is reduced but it still remains. The API ref layout of the page header still differs slightly from the rest of the site.

**Comment by willeastcott** [comment]
Very nearly fixed. PLAYCANVAS MANUAL still misaligned for API ref. Some other tiny differences too.

**Comment by willeastcott** [comment]
Seems fixed now. Hurrah.
