### ISSUE TITLE
app.renderLines

### ISSUE THREAD

**Issue by Cr0c81** [playcanvas/developer.playcanvas.com#114]
"Draw an array of lines" broken curve must be, not independed lines. Need detailed description.
https://developer.playcanvas.com/en/api/pc.Application.html#renderLines

**Comment by LeXXik** [comment]
Just a bit of a clarification. The suggestion here is to add a description that the array of lines are not describing a single continuous line, like a curve, but a series of independent lines. The array holds positions in pairs, describing a start and an end of each line, with the corresponding colors describing their gradients.

The current description suggests a single line would be drawn through the provided positions.
