### ISSUE TITLE
Feature request: Playcanvas media assets

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/developer.playcanvas.com#122]
Not sure where to put this request, so feel free to relocate to an appropriate place.

I would like to request to add a Media section to the resources, which would share the Playcanvas logotypes. Currently, if i want to add a Playcanvas logo to some posting or a document, I have to draw one myself or google a version that was drawn by someone else. 

It would be nice, if there would be an official variant available for download with the branding colors and variants.

**Comment by yaustar** [comment]
Done as https://github.com/playcanvas/developer.playcanvas.com/pull/399
