### ISSUE TITLE
Multiplayer tutorial no longer works

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#123]
Thread: https://forum.playcanvas.com/t/about-multiplayer/14537

> The code is different in the tutorial than in the example project. For example the tutorial code uses this.id when the example code uses Network.id

**Comment by jarileon** [comment]
Is there any estimate on this @yaustar? The lack of comma support makes using the editor quite irritating when typed numbers resolve to 0
