### ISSUE TITLE
Button page in the User Manual links to the incorrect button API page

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#128]
https://developer.playcanvas.com/en/user-manual/packs/components/button/ links to https://developer.playcanvas.com/en/engine/api/pc.ButtonComponent.html

**Comment by vkalpias** [comment]
Why is this a bug? I think the link refers to the scripting interface of the button component which correctly points to the API docs?

**Comment by yaustar** [comment]
Errr... Good question. Maybe this was fixed? I think the Script link pointed to the Button API
