### ISSUE TITLE
First person movement tutorial is missing image

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#130]
See thread: https://forum.playcanvas.com/t/outdated-broken-links/15025/3?u=yaustar

**Comment by GamerWael** [comment]
Actually I don't think this is a problem because the image is displayed on the fps movement page of the developer.playcanvas.com website. It's showing a 404 only when you click the link in the GitHub file. In fact all of the image links in the readme files are showing 404
