### ISSUE TITLE
Duplicate function names look ugly

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/developer.playcanvas.com#16]
Currently, for multiple function signatures, we have (for pc.Entity say):

setPosition
setPosition^2

We need a better way of handling this.

**Comment by vkalpias** [comment]
We could do something like show the function name and then for each declaration do [1] [2] [3] etc where each number is a link

**Comment by willeastcott** [comment]
One option is to have a single entry to a function in the Summary section (e.g. setPosition) and in the Details section, have all signatures without the ^N. And the link function name in the Summary section links to the first prototype.

**Comment by willeastcott** [comment]
I've fixed this by documenting different function signatures in a single JSdoc block.
