### ISSUE TITLE
Make the User Manual sub sections easier to navigate and link to

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#166]
When giving users a link to a particular subsection of the User Manual, we have to tell them roughly where on the page it is as there is no easy reference link to unlike the API pages. (eg trying to link to ‘Updating Templates’ on the ‘Templates’ page (https://developer.playcanvas.com/en/user-manual/templates/)). 

It be great to an icon or URL link to copy instead.
![image](https://user-images.githubusercontent.com/16639049/98832973-64539d00-2435-11eb-9239-0bf4f0c6ad01.png)

**Comment by willeastcott** [comment]
This would be good, for sure. But FYI, you can do this:

![link](https://user-images.githubusercontent.com/697563/98837040-5d7b5900-243a-11eb-8b59-5514c1509e54.gif)
