### ISSUE TITLE
Keep the search bar at the top of window

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#169]
As you go down the page in the documentation sections, the search bar scrolls off the page. It be nice for it to always be at the top to save scrolling up.

![Kapture 2020-09-23 at 17 02 08](https://user-images.githubusercontent.com/16639049/98834360-06c05000-2437-11eb-82f6-edaafc64df03.gif)

**Comment by willeastcott** [comment]
The new [TypeDoc-based API Reference](https://api.playcanvas.com/) renders this issue obsolete. You now just press '/' to activate search.
