### ISSUE TITLE
Update documentation for use_local_engine

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#178]
Now that we have limited it to code.playcanvas.com and localhost, this page needs to be updated: https://developer.playcanvas.com/en/user-manual/scripting/custom_engine/

Also we need to write docs around the editor setting Local Server property:

![image](https://user-images.githubusercontent.com/16639049/99282315-706f9e00-282b-11eb-9291-2e5dc07e3b1d.png)

**Comment by vkalpias** [comment]
This page https://developer.playcanvas.com/en/user-manual/scripting/custom_engine/ doesn't mention anything about setting URLs other than localhost or code.playcanvas.com so seems OK to leave as is?

The Local Server field only applies to legacy scripts I believe

**Comment by yaustar** [comment]
Yeah, I mis understood this parameter. We should hide this option on Script 2.0 projects.
