### ISSUE TITLE
Regarding handling of projects (much needed search function?)

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/developer.playcanvas.com#182]
Hello. This is the top project list of one of my users:
![image](https://user-images.githubusercontent.com/6838800/99905644-6558ba00-2cd2-11eb-8714-fdd35d4dd92b.png)
 - within many of them, I try hard to make telling titles for them in order to find/open certain projects in the process of revisiting them. Many of times I work on one project, for then to close it, in order to work on another. This adds up to irritation, and now I am also using a strategy where I keep six projects open (in the browser), in order to be sure I can find them again (I have around 50 projects in all, and many of them have several scene-effects below them as well).

Solution (and thereby 'feature request' for the website): Can the overview page be made with a search function that lists projects on search words/queries upon project descriptions as well? (for now there is a top limit of 32 letters in the project title, and I can only do so much within 'smart shortenings' within that naming limit :-/ )

// on before hand; thanks

**Comment by yaustar** [comment]
This feature request should be under the Editor repo. developer.playcanvas.com is just for documentation.

**Comment by willeastcott** [comment]
Yes, please log this request [here](https://github.com/playcanvas/editor/issues), @FutureFireplace.

**Comment by FutureFireplace** [comment]
Perfect, thanks ... I will do that
