### ISSUE TITLE
Show where to get common param data for REST API (eg what is a branch id?)

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#197]
We don't really explain how to get the branch_id, project_id, scenes etc. Would be handle to for users to know where to get that.

**Comment by vkalpias** [comment]
The branch_id you can get from the version control window, however the scene id and project id depend on which page you're viewing so it's not as straightforward. Would it be better to add an info box somewhere in the Editor that shows all that data straight away?

**Comment by yaustar** [comment]
It would be great if it's all findable at a single 'place'. Eg this dialog box
![image](https://user-images.githubusercontent.com/16639049/104019648-d3d6d600-51b3-11eb-948f-f425a9a10916.png)

On the REST API page, we should tell users that they can find the branch_id by going to version control and copying the GUID (with images) for example.

**Comment by yaustar** [comment]
Page has been added here: https://developer.playcanvas.com/en/user-manual/api/#parameters
