### ISSUE TITLE
API Reference sources - move to this repo

### ISSUE THREAD

**Issue by Maksims** [playcanvas/developer.playcanvas.com#200]
Currently, it is not possible to contribute to https://developer.playcanvas.com/en/api/ as it is not part of this repository.

Would be great to have it part of this repository, by that be able to contribute to styling of docs generated, JS and CSS of API Reference pages, so we can fix long lasting issues and make API Reference mobile friendly as well (currently it is barely mobile friendly).

**Comment by yaustar** [comment]
Just to check, you would like to move the repo https://github.com/playcanvas/playcanvas-jsdoc-template into this repo?

**Comment by Maksims** [comment]
> Just to check, you would like to move the repo https://github.com/playcanvas/playcanvas-jsdoc-template into this repo?

Hah, I probably had just to look for it. It's naming and based on stars/watches, seems its hidden out there. This repo "developer.playcanvas.com" named like it is everything under this domain. So makes sense to be part of one repo?

**Comment by willeastcott** [comment]
Well, it's split out because it's not inconceivable it'll be used by other projects. We didn't decide to use it for PCUI in the end - but we could have done. 😄
