### ISSUE TITLE
Soft shadow option no longer on the material, but on the light instead

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#209]
This page section is outdated now: https://developer.playcanvas.com/en/user-manual/graphics/lighting/shadows/#soft-shadows-vs-hard-shadows

**Comment by vkalpias** [comment]
Fixed in https://github.com/playcanvas/developer.playcanvas.com/commit/d92fad0c09853941e28ed9cca504e3f9186fd43b (accidentally pushed directly to master)
