### ISSUE TITLE
Add documentation about the Localisation property on font assets

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#211]
This allows a font asset to have overrides depending on the locale so a single asset with all glyphs isn't always needed

eg: https://playcanvas.com/project/752281/overview/multifont-language

**Comment by vkalpias** [comment]
Docs for this are here https://developer.playcanvas.com/en/user-manual/user-interface/localization/

**Comment by yaustar** [comment]
Ah, I missed that. We need more pictures on that page :)
