### ISSUE TITLE
Update terrain generation tutorial to use the new pc.Mesh API

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#247]
https://developer.playcanvas.com/en/tutorials/terrain-generation/

See fix in this post here: https://forum.playcanvas.com/t/terrain-generator-trims-mesh-if-exceeding-65k-vertices/18737/10?u=yaustar

**Comment by mvaligursky** [comment]
this should work fine now, as pc.createMesh internally already uses mesh API.
