### ISSUE TITLE
Alternative to use of AWS server

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/developer.playcanvas.com#260]
Hello, here is a list of alternatives to laying on Amazon's AWS server: https://www.cloudhealthtech.com/blog/aws-alternatives
Personally I don't like paying my monthly fee to a socially regressive company like Amazon.
Yes, they are cheap and efficient, but there traditional stockholder mentality is  ... (here I choose to restrain myself).

The list above claims that Google Cloud can compete on price -  why are 'we' not having our cloud over there instead? :-)

//br

**Comment by willeastcott** [comment]
I don't see how this is relevant to the PlayCanvas Developer Site. Closing.

**Comment by FutureFireplace** [comment]
Ok, where to write about it then :-)

**Comment by willeastcott** [comment]
Well, in your first message, you didn't link to the problem with this repository specifically. What exactly needs to be changed? PlayCanvas is for developing an application's front-end. It's completely agnostic to back-end infra (AWS, Azure, etc).

**Comment by FutureFireplace** [comment]
Ok. Don't bother. Fine - just a suggestion.

**Comment by yaustar** [comment]
@FutureFireplace are you suggesting that PlayCanvas changes where the service/editor/etc is hosted away from AWS?

**Comment by willeastcott** [comment]
If this _is_ about the host for the PlayCanvas service, then the forum is the place for this discussion.

**Comment by FutureFireplace** [comment]
ok, in that case ... I might be a bit more politically oriented than most, but if we transfer to Google Cloud, we avoid connections to Amazon lack of ethics in general (https://www.theguardian.com/technology/2020/feb/05/amazon-workers-protest-unsafe-grueling-conditions-warehouse)
Furthermore we might want to find if our data - on any cloud - can become safe from CME-events (https://en.wikipedia.org/wiki/Coronal_mass_ejection#Future_risk) in the size of the Carrington-event (https://www.youtube.com/watch?v=hESunUuFrzk). Personally I have more than 30gb laying in the PC/AWS-cloud (also after downloading ca 12 gb on magnetic external HDD), and it is quite hard to save it on optically/DVD's.
PS: I am not a 'prepper type', and I am seriously concerned - how is my bank/the banks for instance covered etc?

**Comment by yaustar** [comment]
> ok, in that case ... I might be a bit more politically oriented than most, but if we transfer to Google Cloud, we avoid connections to Amazon lack of ethics in general (https://www.theguardian.com/technology/2020/feb/05/amazon-workers-protest-unsafe-grueling-conditions-warehouse)

Unfortunately, Google aren't free from political issues either: https://www.npr.org/2021/01/08/954710407/at-google-hundreds-of-workers-formed-a-labor-union-why-to-protect-ourselves

Unless there is very good reason to move cloud services, it is unlikely we will do so and favour to continue focusing on developing new features.  

> CME
NASA are using AWS services to help predict said storms so I would assume that they have some mitigation plans: https://www.amazon.science/how-nasa-uses-aws-to-protect-life-and-infrastructure-on-earth

And would like to think that data would be backed across geo locations with most cloud services.

**Comment by FutureFireplace** [comment]
ahh ok ... was busy so I did read "then the forum is the place for this discussion"
as "then the _this_ is the place for this discussion"
