### ISSUE TITLE
Grammar error on Physics' Basics page

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#261]
https://github.com/playcanvas/developer.playcanvas.com/blob/master/content/en/user-manual/physics/physics-basics.md

"the functions will not have an effect. Instead, you must call the teleport function on the rigid body component which explicitly notifies the physics engine you want to momentarily update a rigid bodies position and/or orientation."

Should be:

"the functions will not have an effect. Instead, you must call the teleport function on the rigid body component which explicitly notifies the physics engine you want to momentarily update a rigid bodies*'* position and/or orientation."

**Comment by willeastcott** [comment]
I think you mean:

"the functions will not have an effect. Instead, you must call the teleport function on the rigid body component which explicitly notifies the physics engine you want to momentarily update a rigid body*'*s position and/or orientation."
