### ISSUE TITLE
Fix take screenshot project sample (Safari Mac)

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#268]
https://developer.playcanvas.com/en/tutorials/capturing-a-screenshot/

Use the engine example render to texture from the camera: http://playcanvas.github.io/#graphics/render-to-texture.html
And the creation of a PNG file from this project: https://playcanvas.com/project/605131/overview/capturing-screenshot-from-camera

Edit: Every second screenshot is upside down on Safari Mac, works fine in Chrome.

**Comment by tanaydimriepigraph** [comment]
Hi Yaustar,
This sample project has been of immense help to us. Although I noticed that this doesn't work on Apple Devices? Specially with Safari and on their touch devices. Any ideas why?

PROBLEM:
- It takes the first screenshot properly. But the second and further screenshots are all either flipped or the same as the first screenshot. (Check the attached image.)
- This works find on Chrome for MacOS but not on iPads/iPhones

It would be of great help if there could be a solution provided for this. Or maybe if you could point me in the right direction.
![image](https://user-images.githubusercontent.com/70152396/132319538-569442a2-18ea-41da-ba72-d89ea8e9e57f.png)

**Comment by yaustar** [comment]
> It takes the first screenshot properly. But the second and further screenshots are all either flipped or the same as the first screenshot. (Check the attached image.)

Looks like it only happens in Safari Mac 🤔 Works fine in Chrome

> This works find on Chrome for MacOS but not on iPads/iPhones

It's probably due to not allowing downloads? You may need to use a native sharing method or open the image in a new tab instead.

**Comment by tanaydimriepigraph** [comment]
> Looks like it only happens in Safari Mac 🤔 Works fine in Chrome

You are correct. It's a problem with Safari on Mac and Chrome + Safari on iPad and iPhones.

> It's probably due to not allowing downloads? You may need to use a native sharing method or open the image in a new tab instead.

I am not entirely sure of that and to be honest I feel that download access isn't the problem. Even though I show downloaded screenshots in the image attached. In my application, I send the image to the host page in a blob and set the src of the image tag to that base64 encoded image data (don't think any access violations play a role there?)

**Comment by yaustar** [comment]
Sorry, maybe I should ask: what specifically doesn't work on iPhones?

**Comment by tanaydimriepigraph** [comment]
Sure, here is some more details about that.

The same problem as the image attached:
- First image is correct
- Second is the same as first but flipped
- Third is the same as first (even If the canvas is updated, camera rotation, etc.)
- Fourth is the same as the second.
...then this keeps repeating.

The same is true for iPads too.

Attaching screenshots downloaded using the "Take Screenshot" button in the project, iOS (14.7.1) Chrome:
![iOS14_7_1_Screenshots](https://user-images.githubusercontent.com/70152396/132336146-3b558885-ea1f-4b0b-9209-fc0171c73f35.png)

**Comment by yaustar** [comment]
Oh ok, so this upside down issues is the same across Safari / Webkit. iPhones don't have a different issue from Desktop Safari?

**Comment by tanaydimriepigraph** [comment]
Correct, the issue is the same across Apple Devices.

**Comment by yaustar** [comment]
Trying to work out if it's a canvas issue (where the render to camera texture is applied to) or a render texture issue 🤔 

I would probably render the render texture to the scene to see what it looks like and if it rotates every other screenshot

**Comment by tanaydimriepigraph** [comment]
Thank you :) 
My understanding was that if [this](https://playcanvas.github.io/#/graphics/render-to-texture) renders on Safari. Then RenderToTexture is fine? Of course unless the implementations are different for the renderToTexture and the screenshot project.

**Comment by yaustar** [comment]
> Thank you :)
> My understanding was that if [this](https://playcanvas.github.io/#/graphics/render-to-texture) renders on Safari. Then RenderToTexture is fine? Of course unless the implementations are different for the renderToTexture and the screenshot project.

Yes, that's the theory. Without looking into it yet, my guess it's related to the canvas where it goes from render texture to PNG

**Comment by yaustar** [comment]
@tanaydimriepigraph This has now been fixed by clearing the context before the screenshot.

**Comment by tanaydimriepigraph** [comment]
Thanks @yaustar, That was super quick and helpful!!
