### ISSUE TITLE
Add documentation for render component / glb templates

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/developer.playcanvas.com#270]
- [x] add render component page, similar to existing model component: https://developer.playcanvas.com/en/user-manual/packs/components/model/
- [x] adjust collision component page, add info on using render component mesh: https://developer.playcanvas.com/en/user-manual/packs/components/collision/
- [ ] add "Convert to GLB' and 'Create Container Assets' options in Asset Tasks https://developer.playcanvas.com/en/user-manual/designer/settings/#asset-tasks
- [x] update asset import page to add details on glb template import, including rules of what happens on re-import with changes in the fbx: https://developer.playcanvas.com/en/user-manual/assets/importing/ @yaustar
- [x] deprecate json model format page https://developer.playcanvas.com/en/user-manual/graphics/file-format/

**Comment by yaustar** [comment]
Render component page added: https://developer.playcanvas.com/en/user-manual/packs/components/render/
Import Hierarch page added: https://developer.playcanvas.com/en/user-manual/assets/import-pipeline/import-hierarchy/
