### ISSUE TITLE
Add extra information about templates preload effects

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#286]
- [x] Templates can now be loaded async
- [x] Templates that don't need to be instantiated at runtime, don't need to be preloaded and saves space / size in config.json

**Comment by Maksims** [comment]
**Question:**
If template asset is set to preload, will it lead to related assets to be preloaded too? Or they will load in async if unchecked preload on them?

**Comment by yaustar** [comment]
That's a good question. @zachpeterpaul, can you help out here please?

**Comment by zachpeterpaul** [comment]
I think when you are dynamically loading something (eg a template asset) that's not preloaded, you need to first manually/dynamically load all dependencies whose 'preload' is unchecked, make sure they all finished loading (using their "on load" callback), and only then load the template asset. I believe this is how PlayCanvas game code is written in other similar cases too.

**Comment by zachpeterpaul** [comment]
Another way to describe this: a template asset only contains entity data, like a PC scene document in mongo. They may have e.g. texture references, but not textures themselves. A dynamically instantiated template allows you to quickly create multiple entities at run time, but you have to make sure yourself that all prerequisites are already available at that point.

**Comment by Maksims** [comment]
Thank you @zachpeterpaul, just to answer on my own question:
1. Template does not keep separate list of referenced assets, and is basically same as a scene - just a hierarchy data.
2. When parsed, it does not do any special logic, and does not trigger preload for related assets.

Means, template, will not trigger load event on related assets, which I believe as a default behaviour - is good! As we want to be able to instantiate template without need to async load it, but we don't want to preload assets, and make engine load them in async when instance of a template becomes used in render.
And developer is free to find referenced assets within template hierarchy and implement own loading behaviour.
