### ISSUE TITLE
Wrong example on pc.scriptType

### ISSUE THREAD

**Issue by leonidas7L** [playcanvas/developer.playcanvas.com#29]
Check the following example code for move():

http://developer.playcanvas.com/en/api/pc.ScriptComponent.html#move

**Comment by willeastcott** [comment]
Hi @leonidas7L. Wow, this is an old issue. I think it might have been fixed since you logged it. Can you confirm?

**Comment by willeastcott** [comment]
Ah! Yes, this has indeed been fixed. See https://github.com/playcanvas/engine/commit/26995d65fd47f8d3c6f443ffaaad57611e36a2ca#diff-8951344824a20679b62ee57e5a753d1e for more details. I'm closing this.
