### ISSUE TITLE
Markdown links in tables aren't being created

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#381]
Seems to be an issue on prod and our staging server: https://developer.playcanvas.com/en/user-manual/introduction/

<img width="833" alt="image" src="https://user-images.githubusercontent.com/16639049/167120908-979a9b47-9089-422a-ab1b-f4cc00ee3150.png">

But building locally doesn't have this problem

<img width="841" alt="image" src="https://user-images.githubusercontent.com/16639049/167120975-8b81e473-2e85-451f-bdf2-ab6be2c76f51.png">

**Comment by willeastcott** [comment]
Just FYI, this is happening because of this bug in marked: https://github.com/markedjs/marked/issues/2217

**Comment by yaustar** [comment]
Should we back out your fix/ workaround too?

**Comment by willeastcott** [comment]
I'm actually fine embedding links in the tables - so I don't think there's much need to switch it back, at least for now.
