### ISSUE TITLE
Add new post effects scripts from the PlayCanvas engine GitHub to the list

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#386]
We have new scripts since we last updated this section: https://github.com/playcanvas/engine/tree/main/scripts/posteffects

Current developer page https://developer.playcanvas.com/en/user-manual/graphics/posteffects/

**Comment by willeastcott** [comment]
I think we'll soon have new post effects courtesy of @mvaligursky, so I think we'll be more likely to remove+deprecate the existing post effects scripts in the not too distant future. We will, of course, document the new post effects when they arrive. Closing.
