### ISSUE TITLE
Add lazy loading attribute to images

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#400]
We should add this attribute to images in the documentation as some pages can be rather image heavy: https://web.dev/browser-level-image-lazy-loading/#the-loading-attribute

**Comment by willeastcott** [comment]
Does this help? 

https://github.com/markedjs/marked/discussions/2441

**Comment by yaustar** [comment]
Yes and we would also need to add it to the HTML img tags that are also used in the documentation (usually done to resize the image on page I think?)
