### ISSUE TITLE
Have GIFs not animate until played to reduce motion on a page

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#405]
Not 100% sure that we need to do this but having the ticket to store the info and libraries.

This looks like a decent drop in solution: https://github.com/adamchaboryk/gifa11y

Example: https://adamchaboryk.github.io/gifa11y/

**Comment by willeastcott** [comment]
Nice idea. But doing this with Docusaurus is probably going to be a pain. So for now, I'm going to close this as a 'Not Planned'.
