### ISSUE TITLE
Render Component docs improvement

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/developer.playcanvas.com#462]
Render Component lists inherited properties, that are hard to digest. Also, if one wants to add a render component of type box, I would assume he would go to render component docs to see what options does it accept when calling `entity.addComponent('render', options)`. At the moment it doesn't show those, and it is not clear where to find them.

![image](https://user-images.githubusercontent.com/5677782/217856597-6b62f424-e243-48c6-ba24-a0907a219256.png)

**Comment by yaustar** [comment]
I believe this was fixed by this PR https://github.com/playcanvas/playcanvas-jsdoc-template/pull/45

**Comment by yaustar** [comment]
In regards to links to on where to find the component I have a on a list to improve the documentation to make it easier to find how to access components objects etc

**Comment by willeastcott** [comment]
Correct @yaustar, the repeated properties are indeed fixed. Check the page again and you'll see that's now resolved. I'm going to close this for now. @LeXXik, would you mind opening a new issue on the engine asking for the `addComponent` options to be documented for each component, please?
