### ISSUE TITLE
English/Grammar issues in Photon Multiplayer tutorial

### ISSUE THREAD

**Issue by yaustar** [playcanvas/developer.playcanvas.com#497]
https://developer.playcanvas.com/en/tutorials/real-time-multiplayer-photon/

```
const PhotonLoadBalancingPlayCanvas = pc.createScript("PhotonLoadBalancingPlayCanvas");
``` 

Should be 
```
const PhotonLoadBalancingPlayCanvas = pc.createScript("photonLoadBalancingPlayCanvas");
```

---

> Create a script asset named photon-loadbalancing-playcanvas.js to the project to initialize Photon.

Should be

> Create a script asset named photon-load-balancing-playcanvas.js to the project to initialize Photon.

This step is also listed twice to create the script.

**Comment by albertvanveen** [comment]
My suggestion is to make it more clear when new code needs to be added. For example, I hadn't noticed that the part in the image below had been added.

![image](https://user-images.githubusercontent.com/52896137/222194274-aa0f4add-22d2-4138-81a0-f347f493f54a.png)
