### ISSUE TITLE
Broken Multiplayer Tutorial - Can't Find Source

### ISSUE THREAD

**Issue by OmarShehata** [playcanvas/developer.playcanvas.com#51]
The multiplayer tutorial is currently broken as described here:

https://forum.playcanvas.com/t/real-time-multiplayer-tutorial/5609

Even though the project is correctly being loaded as https, the socket.io server calls it's making are to http, thus the mixed content is blocked.

I can fix this but I can't find the project page for this demo. I also think it would be better to put the server on Glitch.com so it's open and easy for people to fork, and simplifies the process of setting it all up.

**Comment by willeastcott** [comment]
The project is here:

https://playcanvas.com/project/406048/overview/tutorial-realtime-multiplayer

I can add you to it if you want to fix it? 😄

**Comment by OmarShehata** [comment]
Sure! I was going to fork it and fix it but I realized there's no way to "merge" it back.

**Comment by willeastcott** [comment]
Cool! I've added you.

**Comment by OmarShehata** [comment]
I've fixed it! I published the build so it should be working on the tutorial page. If you want to confirm it works you can close this issue too. 

https://developer.playcanvas.com/en/tutorials/real-time-multiplayer/
