### ISSUE TITLE
Change the example description

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/developer.playcanvas.com#529]
https://developer.playcanvas.com/en/tutorials/physics-with-ccd/

The ccd.js script describes a Motion Threshold attribute as.
```
Number of meters moved in one frame before CCD is enabled
```

The `one frame` should be changed to `one simulation step`, as Ammo might not step every frame.

**Comment by willeastcott** [comment]
OK, sounds reasonable. Did you want to do a PR to address this?

**Comment by LeXXik** [comment]
I don't think I can do a PR to projects.

**Comment by willeastcott** [comment]
Ah yeah. I've fixed it myself. Thanks for the suggestion.
