### ISSUE TITLE
PostEffects User Manual is Obselete

### ISSUE THREAD

**Issue by sethgillett** [playcanvas/developer.playcanvas.com#53]
The section for post-effects in the user-manual describes a method of adding builtin post-effects which no longer works:

https://developer.playcanvas.com/en/user-manual/graphics/posteffects/

**Comment by sethgillett** [comment]
Am I missing something obvious here?

**Comment by willeastcott** [comment]
Sorry, I don't understand. The line above same this was closed since it's been fixed in [this commit](https://github.com/playcanvas/developer.playcanvas.com/commit/0bedf0acc2f9827d507a33f1e11104452518725c).

**Comment by sethgillett** [comment]
Oh my apologies, I'm kinda new to Github so I thought it had been closed without a fix. Thanks!

**Comment by willeastcott** [comment]
No worries. Thanks for reporting this!

**Comment by willeastcott** [comment]
The fix is now [live](https://developer.playcanvas.com/en/user-manual/graphics/posteffects/).
