### ISSUE TITLE
Migrate Developer Site to a modern static site generator

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/developer.playcanvas.com#534]
The current developer site is built on [Metalsmith](https://metalsmith.io/). It has not changed significantly in over 10 years. It has the following problems:

* The build process is extremely brittle and convoluted. Custom plugins have been written to build the site's sidebar tree and localization. Most modern site generators handle sidebars and localization out of the box.
* The developer experience is poor. The watch process doesn't work well and you normally have to cancel the serve command to rebuild and then restart it. No hot reload!
* The current developer site is not responsive for mobile.
* We can't easily theme the site or enable a dark mode.

I propose migrating the whole site to something superior to Metalsmith. After doing some research, I propose [Docusaurus](https://docusaurus.io/). It offers:

* Hot reload.
* Breakcrumbs on each generated page.
* Page TOC generation (like a 'minimap' on the right).
* 'Edit page on GitHub' links.
* Light + dark mode.
* Next/Prev buttons per-page.
* Out-of-the-box support for sidebar construction and localization.
* Easy custom page creation via React.
* Responsive design across mobile + desktop.

**Comment by Maksims** [comment]
Another thing would be important, is a better quick filter bar, as well as better search.
Current search is misleading and is not great at all. And just tested, it does not even work on mobile.

**Comment by marklundin** [comment]
Yep agreed. There is 3rd party [Algolia](https://www.npmjs.com/package/algoliasearch) search tool which I've seen in many doc sites. Seems very fast and great dev experience
