### ISSUE TITLE
s3 pages indexed in google

### ISSUE THREAD

**Issue by OlegGedzjuns** [playcanvas/developer.playcanvas.com#558]
Search request: blur texture playcanvas

In search results, I see http://developer.playcanvas.com.s3-website-eu-west-1.amazonaws.com/ pages

![chrome_D58VaCcMdq](https://github.com/playcanvas/developer.playcanvas.com/assets/41446646/1fbc81c1-20e4-4301-a390-f4a8ea5e7ee5)

when trying to access them, Google Chrome shows a safety warning

![image](https://github.com/playcanvas/developer.playcanvas.com/assets/41446646/b15d68fb-d76d-4232-bebc-29d2976e5f3d)

possibly, indexing should be disabled for s3 pages

**Comment by willeastcott** [comment]
Once this new Docusaurus-based developer site goes live (hopefully in the next few days), this will no longer be an issues because it will be hosted on GitHub pages. 😄

**Comment by Maksims** [comment]
> Once this new Docusaurus-based developer site goes live (hopefully in the next few days), this will no longer be an issues because it will be hosted on GitHub pages. 😄

Probably still worth updating existing S3 files with "norobots" header, to ensure google picks up on it. Otherwise they can stay there for a long time.

**Comment by OlegGedzjuns** [comment]
@willeastcott I hope super useful/fast filter will still be there
![image](https://github.com/playcanvas/developer.playcanvas.com/assets/41446646/ec7981b5-9f9e-4970-a041-0b7991871b14)
