### ISSUE TITLE
Move 'Using a Custom Engine' to more appropriate place

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/developer.playcanvas.com#564]
Currently this is part of `Scripting` section, but it's not related to scripting at all.

<img width="271" alt="Screenshot 2024-01-24 at 15 42 43" src="https://github.com/playcanvas/developer.playcanvas.com/assets/59932779/10c0642c-b340-47c5-8022-4ba39888d375">

**Comment by willeastcott** [comment]
We probably need a new section on the Launch Page.

**Comment by willeastcott** [comment]
OK, I've added a page on the [Launch Page](https://developer.playcanvas.com/user-manual/editor/launch-page/). I could add it as a child of that page. What do you think @mvaligursky?

**Comment by mvaligursky** [comment]
Yep that would work well @willeastcott .
By the way, the first screenshot on that new Launch Page has the `Prefer WebGPU` on it, which is not public at the moment. Not a big deal though.
