### ISSUE TITLE
Broken project of Real Time Multiplayer tutorial page

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/developer.playcanvas.com#656]
The project of the Real Time Multiplayer tutorial page seems to be broken.

Multiple users have report this on the forum as well.

Link to page:
https://developer.playcanvas.com/tutorials/real-time-multiplayer/

Link to project:
https://playcanvas.com/project/406048/overview/tutorial-realtime-multiplayer

Errors of console:
![image](https://github.com/playcanvas/developer.playcanvas.com/assets/52896137/cd362d32-2a0b-4c65-8d41-a8f6e3b6eef8)

**Comment by willeastcott** [comment]
Note: when this is fixed, update [this forum thread](https://forum.playcanvas.com/t/the-real-time-multiplayer-forms/35853/2).

**Comment by albertvanveen** [comment]
Here is also another related topic: https://forum.playcanvas.com/t/cant-see-other-people-in-multiplayer/

**Comment by albertvanveen** [comment]
Can someone please fix this project, as I think it is very useful compared to alternatives.

It feels uncomfortable to share the page when users ask for some help.

![image](https://github.com/user-attachments/assets/485fd044-fec5-4af0-8ede-a0dd7b1f6ce2)

**Comment by willeastcott** [comment]
@albertvanveen Thanks for bumping this. I believe I have significantly improved and fixed the tutorial now. Let me know if you think I have missed anything.

**Comment by albertvanveen** [comment]
That's perfect, thanks a lot! 🙏

I will give it a try myself when I have some time. 👌
