### ISSUE TITLE
Tutorial - Creating a Music Visualizer - Music file removed

### ISSUE THREAD

**Issue by ViniciusFXavier** [playcanvas/developer.playcanvas.com#83]
Tutorial: https://developer.playcanvas.com/en/tutorials/music-visualizer/

The song that was supposed to play in the example has been removed from the soundcloud, need fix.

Removed -> https://soundcloud.com/overwerk/daybreak-h3

**Comment by yaustar** [comment]
The MP3 is in the project itself, the SoundCloud link was needed as part of the license perhaps?

There's a separate issue on why the the music doesn't play sometimes.
