### ISSUE TITLE
FEATURE REQUEST - Addition of GoNative.io as a mobile publication option in docs. 

### ISSUE THREAD

**Issue by renegadels** [playcanvas/developer.playcanvas.com#98]
Hello, 

In this(https://developer.playcanvas.com/en/user-manual/publishing/mobile/) documentation page, the options for mobile publishing are rather small, and not always reliable for larger projects. I'd like to suggest adding https://gonative.io as an option, as all that's required is copy-pasting the URL and then changing a few properties via a simple interface. I can confirm that this works perfectly.

**Comment by yaustar** [comment]
We now have a page on how to use Cordova https://developer.playcanvas.com/en/user-manual/publishing/mobile/cordova/
